### PR TITLE
Greyscaled tab indicator.

### PR DESCRIPTION
**Pull request by isoos**
screen shot 2018-07-02 at 13 54 09

Black: active tab
Gray: on-hovering

/cc @mit-mit

### CODE REVIEW

**Comment by mit-mit** [comment]
It looks a bit odd with the blue text and black highlight bar. Can you try to make the text black?

**Comment by isoos** [comment]
>  Can you try to make the text black?

The text is already black, but we can make the rest of the tabs lighter, and the selected one bold. What about this?

screen shot 2018-07-02 at 14 05 51

**Comment by isoos** [comment]
Although the bolding makes the line a bit to "move" on tab switching, and it is not bad without bold either:

screen shot 2018-07-02 at 14 08 57

**Comment by mit-mit** [comment]
Last example (black, no bold) LGTM!

**Comment by isoos** [comment]
> The indention style looks a tiny bit inconsistent in this stylesheet.

It is, as it is a mixture of an old style, a new design which was handed to us, and our additional updates. I'm trying to make it more consistent (two tabs), but looks like I've missed it this time, will fix.

**Pull request merged**
