### PR TITLE
Add a special package name that causes a 500 response – useful for testing

### PR DESCRIPTION
**Pull request by kevmoo**
CC @nex3 – would this be useful? If we wire up the pub client for such logic, It'd be good to make sure it works consistently

### CODE REVIEW

**Comment by isoos** [comment]
Is the big change in `app/test/frontend/handlers_test.dart` indenting? Hard to tell from the diff.

**Comment by kevmoo** [comment]
> Is the big change in app/test/frontend/handlers_test.dart indenting? Hard to tell from the diff.

Sorry to blend commits. Look at the 2nd commit. Easier to see.

**Comment by nex3** [comment]
I don't know that this would provide us much value... we test against local servers, not against the live site, and we can always set those up to return whatever status codes we want.

**Comment by kevmoo** [comment]
ack!

**Pull request closed without merging**
