### PR TITLE
Fix NPE in search qualifier handling.

### LINKED ISSUE #891: packages that depend on a packge web page broken for all packages
for example:

https://pub.dartlang.org/packages/web_socket_channel

then choose the hyperlinekd text: "Packages that depend on web_socket_channel", which navigates to:
https://pub.dartlang.org/packages?q=dependency%3Aweb_socket_channel

### PR DESCRIPTION
**Pull request by isoos**
- Added test to catch the error next time.
- Fixes #891

### CODE REVIEW

**Comment by isoos** [comment]
@jakobr-google can you do a publish or shall we wait for @kevmoo ?

**Comment by kevmoo** [comment]
Deploying now...waiting for my coffee...

**Comment by kevmoo** [comment]
Deployed! https://pub.dartlang.org/packages?q=dependency%3Aweb_socket_channel

**Comment by isoos** [comment]
thanks!

**Pull request merged**
