### PR TITLE
Update highlight.js languages

### PR DESCRIPTION
**Pull request by kevmoo**
Removes objectivec, swift, java

Aligning with similar change in dartdoc: https://github.com/dart-lang/dartdoc/pull/1489

### CODE REVIEW

**Comment by isoos** [comment]
Why remove ` objectivec, swift, java`? Wouldn't a flutter plugin contain code in such languages, maybe putting a snippet in the readme?

**Comment by kevmoo** [comment]
Oh...yeah...good point.

**Comment by mkustermann** [comment]
I guess you want add the 3 languages again? Let me know when it's ready for review.

**Comment by kevmoo** [comment]
Yup. Give me a minute...

On Thu, Aug 31, 2017 at 1:01 AM, Martin Kustermann <notifications@github.com

**Comment by kevmoo** [comment]
I'll make sure to update dartdoc now – so I'm glad I messed up 😄 

Thanks for catching it...

**Pull request merged**
