### PR TITLE
Add link to Crossdart on the pkg/show page

### PR DESCRIPTION
**Pull request by astashov**
**Note**: I didn't test it, it's pretty hard to run it locally, it depends on Google Cloud account heavily.
But it type checks! :)

Crossdart contains the hyperlinked source code of all the packages on
pub. Somewhat like dartdocs.org, but in case you want to read the source
code of a package instead of its documentation :)

It gonna look like this:

image

/cc @filiph

### CODE REVIEW

**Comment by filiph** [comment]
We might want to call this "Source code (hyperlinked)" on the page, not "Crossdart".

**Comment by astashov** [comment]
Makes sense, will change.

**Comment by astashov** [comment]
Fixed

**Comment by filiph** [comment]
Since this is not tested, I'd like someone familiar with the codebase to lgtm this.
// cc @kevmoo

**Comment by mkustermann** [comment]
LGTM

**Comment by mkustermann** [comment]
The change is live. The hyperlinked source is really nice :)

**Comment by astashov** [comment]
Awesomeness! Thank you very much!

**Pull request merged**
