### PR TITLE
Simplify search snapshot loading.

### PR DESCRIPTION
**Pull request by isoos**
Please check the prod bucket that it contains the fixed-named snapshot file before merging this.

### CODE REVIEW

**Comment by mkustermann** [comment]
Currently it's not there:
```
$ gsutil ls gs://dartlang-pub-dev--search-snapshot/                       
gs://dartlang-pub-dev--search-snapshot/snapshot-2017-10-29T13-08-14.256841Z.json.gz
```

**Comment by isoos** [comment]
I'm not worried about dartlang-pub-dev (I've deployed a new version only recently, it is normal it is not there yet), I only worry about prod.

**Comment by mkustermann** [comment]
It seems to be on the prod bucket:
```
$ gsutil ls gs://dartlang-pub--search-snapshot/   
gs://dartlang-pub--search-snapshot/snapshot-2017-10-31T15-25-37.785240Z.json.gz
gs://dartlang-pub--search-snapshot/snapshot-latest.json.gz
```

**Comment by mkustermann** [comment]
Travis seems to be broken atm :-/

**Pull request merged**
