### PR TITLE
More packages link on the landing page.

### PR DESCRIPTION
**Pull request by isoos**
I couldn't decided on where to put these links, and until a better one emerges, these should be fine.

screen shot 2017-12-19 at 5 03 37 pm

### CODE REVIEW

**Comment by kevmoo** [comment]
I'm not a huge fan of this. I find it a tiny bit confusing. I think having the drop-down on the results page is sufficient.

@mit-mit ?

**Comment by isoos** [comment]
> I find it a tiny bit confusing. 

Agreed.

> I think having the drop-down on the results page is sufficient.

There is some demand for something like this: https://gitter.im/dart-lang/TALK-general?at=5a38d34b0163b02810545a86

**Comment by isoos** [comment]
any decision yet on how to proceed with this?

**Comment by kevmoo** [comment]
@mit-mit ?

**Comment by mit-mit** [comment]
I don't think we need to complicate the front page given this is available on the general sort page.

**Pull request closed without merging**
