### PR TITLE
 Custom package description extensions.

### PR DESCRIPTION
**Pull request by isoos**
Definitely improved angulardart -> angular result, but I wasn't able to check it on prod index.

### CODE REVIEW

**Comment by mkustermann** [comment]
I really don't know if this is the right approach. I mean every package author could say: I'd like package X rank higher when searched for Y. So we would continue to add more terms to the description.

How about just publishing a new angular package with the desription in it? Or adding (with coordination with the pub client devs) a `keywords: ` to the `pubspec.yaml`?

**Comment by isoos** [comment]
> How about just publishing a new angular package with the description in it?

+1

> Or adding (with coordination with the pub client devs) a keywords: to the pubspec.yaml?

What would you put in `keywords` which you wouldn't put in `description`? Related request: https://github.com/dart-lang/pub-dartlang-dart/issues/368

**Comment by mkustermann** [comment]
> What would you put in keywords which you wouldn't put in description? Related request: #368

I would consider `description` like human readable text (i.e. sentences) whereas `keywords` as  structured data (not natural language), i.e .machine-readable.

**Comment by isoos** [comment]
Closing PR, I plan another way of addressing this.

**Pull request closed without merging**
