### PR TITLE
Phrase highlight for search results.

### LINKED ISSUE #465: To discuss: highlight "exact matches" in search
See https://crates.io/search?q=winapi

If the search string exactly matches a package, highlight it on top

Wondering if this would be useful?

### PR DESCRIPTION
**Pull request by isoos**
Closes #465.

screen shot 2017-12-12 at 6 02 01 pm

### CODE REVIEW

**Comment by kevmoo** [comment]
Now that I see this, I'm not sure I like it.

@mit-mit ?

**Comment by mit-mit** [comment]
I think that looks quite busy indeed. Did search engines used to do that, but removed it as it was too distracting. I usually just do a find in the page myself...

**Comment by isoos** [comment]
The style can be more subtle and faded, but I'm happy to close this if that is the consensus.

**Comment by isoos** [comment]
screen shot 2017-12-14 at 9 39 21 am

Alternative style, less busy. @mit-mit @kevmoo ?

**Comment by mit-mit** [comment]
I'm still not convinced it's worth it, still looks busy and (subjectively) a bit "old school". If a customer wants highlighting, they can just use the browser 'search in page' feature.

**Pull request closed without merging**
