### PR TITLE
Upgrade dependencies for better Dart2 compatibility.

### PR DESCRIPTION
**Pull request by isoos**
Deploy to staging is ongoing.

### CODE REVIEW

**Comment by isoos** [comment]
staging looks good, merging

**Comment by sortie** [comment]
Sounds good. Let me know when you'd like this change to be deployed to production.

**Comment by isoos** [comment]
Generally we don't prefer to do deploys on Friday and on the weekend, unless it is really urgent. Please do deploy this to prod on Monday, there are no breaking changes anywhere, should be straightforward.

**Comment by sortie** [comment]
Yep, I can do that. I'm on Vacation Monday and Tuesday is a national holiday, so I won't be able to deploy it until Wednesday next week.

**Comment by isoos** [comment]
Sounds good!

**Pull request merged**
