### PR TITLE
Host-based frontend memcache keys with invalidations on pub.dartlang.org

### LINKED ISSUE #768: Create some model to selectively skip memcache
So we can validate a deployment...

### PR DESCRIPTION
**Pull request by isoos**
Closes #768

### CODE REVIEW

**Comment by mkustermann** [comment]
Couldn't we just prefix the memcache entries with the deployment version (which is always the same for a given instance) instead of deriving the memcache prefix from the incoming requests?

**Comment by isoos** [comment]
> Couldn't we just prefix the memcache entries with the deployment version (which is always the same for a given instance) instead of deriving the memcache prefix from the incoming requests?

But then an upload that happens on a non-migrated or a partially migrated instance wouldn't clear the cache on all of the prod instances.

**Comment by kevmoo** [comment]
> Couldn't we just prefix the memcache entries with the deployment version (which is always the same for a given instance) instead of deriving the memcache prefix from the incoming requests?

@mkustermann – I had a similar idea, but we'd have to get pretty crazy w/ our cache invalidation logic.

This is a simple first step so we can sanity check a deploy before making it default.

**Comment by mkustermann** [comment]
Well, I'm not a big fan of this. Our invalidation logic will still be unable to invalidate all keys in memcache.

We could just override the memcache service in the service scope to be a NOP cache if the URL has a specific get parameter or if the requested url is not `pub.dartlang.org`. Then we'll always get up-to-date versions of the page.

**Comment by isoos** [comment]
> We could just override the memcache service in the service scope to be a NOP cache if the URL has a specific get parameter or if the requested url is not pub.dartlang.org.

I've considered not caching when the URL is not `pub.dartlang.org`, but then if there is an issue with the caching logic, we wouldn't notice it during validation of a new release.

**Comment by kevmoo** [comment]
Let's punt on this for now, given the alternative...

**Pull request closed without merging**
