### PR TITLE
GitHub Markdown CSS as a separate file.

### PR DESCRIPTION
**Pull request by isoos**
https://github.com/dart-lang/pub-dartlang-dart/issues/871

### CODE REVIEW

**Comment by isoos** [comment]
> Have this been tested in all the relevant browsers?

Chrome and Firefox on Mac looks good.

> Do you have a browser screenshot tool available btw? I can look for whether we have one internally

Deployed to staging:
https://dartlang-pub-dev.appspot.com/packages/flutter_blue

**Comment by sortie** [comment]
The font rendering on https://dartlang-pub-dev.appspot.com/packages/flutter_blue#-readme-tab- looks fairly bad (aliased) on my Linux Firefox 52.8.1 (64-bit).

However, this is how github does look in that browser. It's probably rather the fault of the Linux distro. So I'm fine with it.

Before:

github-css-linux-firefox-before

After:

github-css-linux-firefox-after

**Comment by sortie** [comment]
It looks better without .markdown-body font-family in Linux Firefox for me. Chrome looks about the same (different font, either looks fine).

**Comment by sortie** [comment]
lgtm

**Pull request merged**
