### PR TITLE
Remove tools: copy_data, datastore.

### PR DESCRIPTION
**Pull request by isoos**
As the backup-restore cycle to update staging seems to be easy, there is no need for tools like the two scripts (which will get outdated soon as we do more model changes).

### CODE REVIEW

**Comment by sigurdm** [comment]
Does this give some datastore tables we can remove?

**Comment by sigurdm** [comment]
I meant cloud storage buckets

**Comment by isoos** [comment]
No, these scripts were working with local files.

**Comment by sigurdm** [comment]
Thanks!

**Pull request merged**
