### PR TITLE
Error header

### PR DESCRIPTION
**Pull request by kevmoo**
I think the first commit is solid.
The 2nd is open for discussion. I think it's nice to be able to force a 500 – thoughts?

### CODE REVIEW

**Comment by kevmoo** [comment]
thoughts, @isoos ?

**Comment by isoos** [comment]
I'm a bit undecided on the forced exception throwing. For how long would you keep that in the source code?

**Comment by kevmoo** [comment]
Well, let me land the response header thing. The error bit I thought would be nice for testing...

**Comment by kevmoo** [comment]
@isoos – down to just the response header now...PTAL

**Pull request merged**
