### PR TITLE
Keep track of package creation time and order by it on the search service

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Comment by kevmoo** [comment]
This is just an *option*, right? It doesn't feed into the default results...

**Comment by isoos** [comment]
> This is just an option, right? It doesn't feed into the default results...

Yeah, I'm working on a separate PR for that.

**Comment by isoos** [comment]
(deferring merge a bit, as it is possible to do the same query with Datastore only, and if there isn't any other requirement for it, it is better leave it out)

**Comment by isoos** [comment]
Closing without merging for now, because home page has roughly the same latency with the Datastore-only version, and otherwise there is no need for this.

**Comment by isoos** [comment]
Re-opening and merging this, because the new homepage concept we have discussed requires the list of newest packages by platform.

**Pull request merged**
