### PR TITLE
Remove withCorrectDatastore, require SDK >=1.25.0-dev.9.0

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by isoos** [comment]
I was waiting for 1.25 release with this. On a related note, how can I make homebrew install the beta SDK?

**Comment by kevmoo** [comment]
There will be no 1.25 release. Only 2.0.0-dev until we ship

You can install latest with `brew install dart --devel`

**Comment by kevmoo** [comment]
...since the site is running on a prerelease, dev might as well, too

**Comment by mkustermann** [comment]
Closing https://github.com/dart-lang/pub-dartlang-dart/issues/350 then.

**Pull request merged**
